<a href="https://colab.research.google.com/github/Guru2308/Deep-Learning-with-PyTorch/blob/main/PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Hello World")

Hello World


In [2]:
!nvidia-smi

/bin/bash: nvidia-smi: command not found


In [3]:
import torch
print(torch.__version__)

2.0.1+cu118


#Introduction to scalars
Creating a tensors


In [4]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [7]:
scalar.item()

7

In [9]:
#Vector
vector = torch.tensor([9,9])
vector

tensor([9, 9])

In [10]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [16]:
#Matrix
MATRIX = torch.tensor([[2,3,4],[3,5]])
MATRIX

tensor([[2, 3, 4],
        [3, 5, 7]])

In [17]:
MATRIX.ndim

2

In [18]:
MATRIX[1]

tensor([3, 5, 7])

In [19]:
MATRIX.shape

torch.Size([2, 3])

In [24]:
#TENSOR
TENSOR = torch.tensor([[[1,12,23],[0,0,0],[99,88,77]]])
TENSOR

tensor([[[ 1, 12, 23],
         [ 0,  0,  0],
         [99, 88, 77]]])

In [25]:
TENSOR.ndim

3

In [22]:
TENSOR.shape

torch.Size([1, 3, 3])

#Random Tensors

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data
-> update random numbers`

In [26]:
#create random tensors
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3925, 0.0107, 0.1367, 0.3257],
        [0.3315, 0.4707, 0.3320, 0.8166],
        [0.5184, 0.3003, 0.9264, 0.7340]])

In [29]:
##create random image tensors
random_image_tensor = torch.rand(size=(3, 224,224))
random_image_tensor
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [30]:
random_tensor.dtype

torch.float32

#Creating a range of tensors